### ISSUE TITLE
Narrow-page menu shifts page.

### ISSUE THREAD

**Issue by gfeiden** [astro-alexis/cs19#18]
For narrow windows or mobile views of the webpage, the "hamburger" menu shifts the entire page down when it is opened. Can we alter this so that it appears to hover above the material below the navigation bar?

Normal, closed menu

![screen shot 2015-07-04 at 15 58 29](https://cloud.githubusercontent.com/assets/3239184/8508169/0abbb8a8-2266-11e5-93d0-6cca8541cc69.png)

Open menu with page pushed down

![screen shot 2015-07-04 at 15 58 08](https://cloud.githubusercontent.com/assets/3239184/8508170/16f2c21a-2266-11e5-863f-648a1abde3b7.png)

**Comment by astro-alexis** [comment]
I see your point. And I think it should not be painful to modify that. I am not convinced it will be better though. When the user activates the menu, it is to see the navigation and change page. Does it matter if the content is below the menu, or under it?
I'll check the code and we'll try the two options monday?
