### ISSUE TITLE
Can't see links to splinters on http://coolstars19.com

### ISSUE THREAD

**Issue by jradavenport** [astro-alexis/cs19#20]
For example, I can manually navigate to the Flares splinter:
http://coolstars19.com/splinters/flares/

but there is no link to the actual sessions on the website

**Comment by astro-alexis** [comment]
Yes. I will send a mail soon to all splinters organizrs tomorrow to get links of the splinters and be sure that wzbsites are ready. So far I have brown dwarfs and magnetism

**Comment by jradavenport** [comment]
Awesome :)

We (the Flares splinter) are happy to have our splinter website still be on the CS19 site, but we will need to update it with a link to a Google Doc submission form, and probably more info as we go. 

Do we just submit Pull Requests to the master branch of the cs19 repo?

**Comment by astro-alexis** [comment]
Absolutely. That's the best way to go. You can also drop me a line if you need help to implement anything, I am usually pretty responsive during usual central European working hours ;).
